## **Práctica 5**

In [1]:
import numpy as np

### **Ejercicio 1**

<img src="https://raw.githubusercontent.com/estuardozapeta/Statistical-Learning-II-Practica-5/master/model1.png">

##### **Definicion de la función sigmoid**

In [50]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

##### **Datos de entrada + bias**

In [53]:
x = np.array([
    [1,2,1],
    [4,3,1],
    [2,4,1],
    [5,1,1],
])

##### **Pesos**

In [58]:
w1 = np.array([ 
    [5,-2,-8], 
    [7,-3,1] 
])

w2 = np.array([7,5,-6])

##### **Calculando la capa intermedia**

In [55]:
h = np.matmul(x,w1.T)
n, m = hidden_layer.shape
H = np.hstack((h, np.ones((n,1))))
output = sigmoid(H)
output

array([[9.11051194e-04, 8.80797078e-01, 7.31058579e-01],
       [9.97527377e-01, 9.99999998e-01, 7.31058579e-01],
       [2.47262316e-03, 9.52574127e-01, 7.31058579e-01],
       [9.99999694e-01, 1.00000000e+00, 7.31058579e-01]])

**Conclusión**: La característica con mayor presencia se representa en el nodo del medio de la capa intermedia.

##### **Salida**

In [61]:
y_aprox = sigmoid(np.matmul(output, w2.T))
y_aprox

array([0.99265773, 0.99768921, 0.9967736 , 0.99432453])

### **Ejercicio 2**

<img src="https://raw.githubusercontent.com/estuardozapeta/Statistical-Learning-II-Practica-5/master/model2.png">

##### **Datos de entrada**

In [64]:
x = np.array([
    [1,1],
    [3,3],
    [2,1],
    [1,2]
])

##### **Pesos**

In [66]:
w1 = np.array([ 
    [0.8,0.2], 
    [0.4,0.9],
    [0.3,0.5]
])

w2 = np.array([0.3,0.5,0.9])

##### **Calculando la capa intermedia**

In [69]:
H = np.matmul(x,w1.T)
output = sigmoid(H)
output

array([[0.73105858, 0.78583498, 0.68997448],
       [0.95257413, 0.98015969, 0.9168273 ],
       [0.85814894, 0.84553473, 0.75026011],
       [0.76852478, 0.90024951, 0.78583498]])

**Conclusión**: La característica con mayor presencia figura en el nodo del medio de la capa intermedia.

##### **Salida**

In [70]:
y_aprox = sigmoid(np.matmul(output, w2.T))
y_aprox

array([0.77438027, 0.83215764, 0.79501858, 0.80026216])

### **Ejercicio 3**